- hosts: all
  become: yes
  gather_facts: true
  roles:
     - base-config

- hosts: appdbs
  become: yes
  gather_facts: true
  roles:
     - geerlingguy.postgresql

- hosts: apps
  become: yes
  gather_facts: true
  roles:
     - app-server

- hosts: frontends
  become: yes
  gather_facts: true
  roles:
     - haproxy

