--- 
- 
  name: http
  package: 
    name: httpie
    state: latest
- 
  name: "install HAProxy"
  yum: "name=haproxy state=latest"
- 
  name: "enable HAProxy"
  service: 
    name: haproxy
    state: started
- 
  name: "configure haproxy"
  template: 
    dest: /etc/haproxy/haproxy.cfg
    src: haproxy.cfg.j2
- 
  name: "restart HAproxy"
  service: 
    name: haproxy
    state: restarted

